### ISSUE TITLE
BUG! Static method don't have to pass self in parameter

### ISSUE THREAD

**Issue by Tezigudo** [oMojiko/progamming-improvement#4]
static method dont have to pass self to argument of it.
please **read more [here](https://www.digitalocean.com/community/tutorials/python-static-method)**
https://github.com/oMojiko/Progamming-improvement/blob/7eeeb251a3cf74b14ba7799edb3806a4cc59927c/Weeks%201/Item_shop.py#L62-L69

**Comment by SeventwoZ** [comment]
Fixed a staticmethod
